import { thisUser } from "../router";
import { Player } from "./engine";
import {
  Mode,
  myName,
  myPlayer,
  shuffle,
  ensureMeFirst,
  sortForRender,
  byId,
  currentMax,
} from "./utils"; 

// Local state
let paired = false;                       // were pairs generated by clicking Matchmaking?
let plannedPairs: [Player, Player][] | null = null; // for 4p preview (randomized semis)
let players: Player[] = [];
let mode: Mode = "2";

// Pairing helpers
function buildFourPlayerPairs(): [Player, Player][] {
  const me = myPlayer();
  const rest = players
    .filter(p => p.name.toLowerCase() !== me.name.toLowerCase())
    .slice(0, 3);
  const bag = shuffle(rest); // randomize the other three
  const semi1: [Player, Player] = [me, bag[0]]; // you always in Round 1
  const semi2: [Player, Player] = [bag[1], bag[2]];
  return [semi1, semi2];
}

// UI state / counters
function updateCounters() {
  const max = currentMax(mode);
  byId<HTMLSpanElement>("count").textContent = String(players.length);
  byId<HTMLSpanElement>("max").textContent = String(max);

  const startBtn = byId<HTMLButtonElement>("btn-start");
  startBtn.disabled = players.length !== max;

  // disable add buttons if we’re at capacity
  byId<HTMLButtonElement>("btn-add-friend").disabled = players.length >= max;
  byId<HTMLButtonElement>("btn-add-guest").disabled = players.length >= max;
}

// Mutations
function addPlayer(name: string) {
  const max = currentMax(mode);
  if (players.length >= max) return;

  const trimmed = name.trim();
  if (!trimmed) return;

  // block adding myself by name
  if (trimmed.toLowerCase() === myName().toLowerCase()) return;

  // prevent duplicates by name
  if (players.some(p => p.name.toLowerCase() === trimmed.toLowerCase())) return;

  const id = `u_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
  players.push({ id, name: trimmed });

  // always re-enforce me at index 0
  players = ensureMeFirst(players);

  plannedPairs = null; // recalc 4p preview if needed
  updateCounters();
  renderMatchmakerPreview();
}

function startTournamentAndGo() {
  const max = currentMax(mode);
  if (players.length !== max) return;

  if (max === 4) {
    if (!paired || !plannedPairs) {
      plannedPairs = buildFourPlayerPairs();
      paired = true;
    }
  } else {
    paired = true; // deterministic
  }

  const payload = {
    mode,
    players,
    pairs: plannedPairs?.map(([a, b]) => [a.id, b.id]) ?? null,
  };
  localStorage.setItem("tournamentSeed", JSON.stringify(payload));
  window.location.hash = "#tournament";
}


// Small UI builders
function createStackedVsBlock(top: string, bottom: string, highlight = false) {
  const wrap = document.createElement("div");
  wrap.className = "flex flex-col items-center justify-center -mt-2";

  const baseColor = "text-violet-500";
  const highlightGlow = highlight ? "drop-shadow-[0_0_6px_#9f7aea]" : "";

  const topName = document.createElement("div");
  topName.textContent = top;
  topName.className = `font-bold text-lg ${baseColor} ${highlightGlow}`;

  const vs = document.createElement("div");
  vs.textContent = "vs";
  vs.className = "text-gray-400 my-1 text-sm";

  const bottomName = document.createElement("div");
  bottomName.textContent = bottom;
  bottomName.className = `font-bold text-lg ${baseColor} ${highlightGlow}`;

  wrap.append(topName, vs, bottomName);
  return wrap;
}

function makeRoundCard(title: string, top: string, bottom: string, highlight = false) {
  const card = document.createElement("div");
  card.className =
    "rounded-2xl border border-violet-400/25 p-4 bg-[#271d35] " +
    "shadow-[0_0_30px_10px_#7037d333] flex flex-col justify-start min-h-[130px]";

  const head = document.createElement("div");
  head.className = "text-base text-gray-200 mb-3 font-semibold";
  head.textContent = title;

  const names = createStackedVsBlock(top, bottom, highlight);
  card.append(head, names);
  return card;
}

//
// Render preview
function renderMatchmakerPreview() {
  const host = byId<HTMLDivElement>("matchgenerator");
  host.innerHTML = "";

  const max = currentMax(mode);

  // participants
  const participantsCard = document.createElement("div");
  participantsCard.className =
    "rounded-2xl border border-violet-400/20 p-4 mb-4 bg-[#271d35] shadow-[0_0_24px_4px_#7037d333]";
  host.appendChild(participantsCard);

  const participantsTitle = document.createElement("div");
  participantsTitle.className = "text-sm text-gray-300 mb-2";
  participantsTitle.textContent = "Participants";
  participantsCard.appendChild(participantsTitle);

  // chips
  const chips = document.createElement("div");
  chips.className = "flex flex-wrap gap-2";
  if (players.length) {
    sortForRender(players).forEach(pl => {
      const chip = document.createElement("span");
      chip.className =
        "inline-flex items-center rounded-lg px-3 py-1 text-sm " +
        "bg-violet-500/15 text-violet-100 border border-violet-400/20";
      chip.textContent = pl.name;
      chips.appendChild(chip);
    });
  } else {
    const none = document.createElement("div");
    none.className = "text-base text-gray-100";
    none.textContent = "No participants yet.";
    chips.appendChild(none);
  }
  participantsCard.appendChild(chips);

  // hint
  const hint = document.createElement("div");
  hint.className = "text-xs text-gray-400 mt-3";
  hint.textContent =
    "You will see your matchups once you reach the required players and press Matchmaking!";
  participantsCard.appendChild(hint);

  // if not enough players, stop here
  if (players.length < max) return;

  // matchup preview cards
  const grid = document.createElement("div");
  grid.className = "grid gap-4 w-full md:grid-cols-3";
  host.appendChild(grid);

  if (max === 2) {
    const [a, b] = players.slice(0, 2);
    if (paired) {
      grid.appendChild(makeRoundCard("Round 1", a.name, b.name));
      grid.appendChild(makeRoundCard("Round 2", a.name, b.name));
      grid.appendChild(makeRoundCard("Final Round", a.name, b.name, true));
    } else {
      grid.appendChild(makeRoundCard("Round 1", "?", "?"));
      grid.appendChild(makeRoundCard("Round 2", "?", "?"));
      grid.appendChild(makeRoundCard("Final Round", "?", "?", true));
    }
  } else {
    // 4 players
    if (paired) {
      if (!plannedPairs) plannedPairs = buildFourPlayerPairs();
      const [s1a, s1b] = plannedPairs[0];
      const [s2a, s2b] = plannedPairs[1];

      grid.appendChild(makeRoundCard("Round 1", s1a.name, s1b.name));
      grid.appendChild(makeRoundCard("Round 2", s2a.name, s2b.name));
    } else {
      grid.appendChild(makeRoundCard("Round 1", "?", "?"));
      grid.appendChild(makeRoundCard("Round 2", "?", "?"));
    }

    grid.appendChild(makeRoundCard("Final Round", "?", "?", true));

    const note = document.createElement("div");
    note.className = "text-xs text-gray-300 mt-1";
    note.textContent = "Winners of Round 1 and Round 2 will be selected in the Final!";
    host.appendChild(note);
  }

  // CTA
  const ctaWrap = document.createElement("div");
  ctaWrap.className = "mt-4 w-full flex justify-end";
  const cta = document.createElement("button");
  cta.className =
    "px-5 py-2 rounded-lg bg-violet-600 hover:bg-violet-500 text-white " +
    "border border-violet-400/30 shadow-[0_0_16px_2px_#7037d355]";
  cta.textContent = "Let’s start 🕹️";
  cta.onclick = () => startTournamentAndGo();
  ctaWrap.appendChild(cta);
  host.appendChild(ctaWrap);
}

//
// Page-level controls
//
function resetPageState() {
  players = [];
  plannedPairs = null;
  paired = false;

  players = ensureMeFirst(players);
  byId<HTMLDivElement>("matchgenerator").innerHTML = "";
  renderMatchmakerPreview();
  updateCounters();
}

function setMode(newMode: "2" | "4") {
  if (mode === newMode) return;
  mode = newMode;
  resetPageState(); // re-add me as Player 1
}

//
// Public initializer — call after you inject LobbyPageTournament() HTML
export function initLobbyPageTournament() {
  // initial mode (radio defaults)
  mode = (document.getElementById("mode-4") as HTMLInputElement).checked ? "4" : "2";

  // wire controls
  const friendInput = byId<HTMLInputElement>("friend-name");
  const addFriendBtn = byId<HTMLButtonElement>("btn-add-friend");
  const addGuestBtn = byId<HTMLButtonElement>("btn-add-guest");
  const startBtn = byId<HTMLButtonElement>("btn-start");
  const mode2 = byId<HTMLInputElement>("mode-2");
  const mode4 = byId<HTMLInputElement>("mode-4");

  addFriendBtn.onclick = () => {
    addPlayer(friendInput.value);
    friendInput.value = "";
  };

  const guestInput = byId<HTMLInputElement>("guest-name");
  addGuestBtn.onclick = () => {
    addPlayer(guestInput.value);
    guestInput.value = "";
  };

  mode2.onchange = () => { if (mode2.checked) setMode("2"); };
  mode4.onchange = () => { if (mode4.checked) setMode("4"); };

  startBtn.onclick = () => {
    const max = currentMax(mode);
    if (players.length !== max) return;

    if (max === 4) {
      plannedPairs = buildFourPlayerPairs(); // (re)roll semifinals
      paired = true;
    } else {
      paired = true;
    }
    renderMatchmakerPreview();
  };

  players = ensureMeFirst(players); // seed "me" if available
  resetPageState();                 // first render
}